commerce_canadapost.settings:
  type: config_object
  label: 'Amazon MWS order settings'
  mapping:
    api:
      type: mapping
      label: 'Information required for connecting to the API'
      mapping:
        customer_number:
          type: string
          label: 'Customer number'
        username:
          type: string
          label: 'Username'
        password:
          type: string
          label: 'Password'
